import Link from "next/link";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: " Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen">
          <header className="w-full p-4 bg-blue-200 text-white">
            <nav>
              <ul>
                <li>
                  <Link href="/products">Products</Link>
                </li>
                <li>
                  <Link href="/shop">shops</Link>
                </li>
              </ul>
            </nav>
          </header>
          <div className="flex-1 p-4">{children}</div>
          <footer className="p-4 bg-slate-100">User RootLayout Footer</footer>
        </div>
      </body>
    </html>
  );
}
