"use client";

import Link from "next/link";
import "../globals.css";
import { usePathname } from "next/navigation";

// export const metadata = {
//   title: "Next.js",
//   description: " Generated by Next.js",
// };

const navLinks = [
  {
    id: 1,
    slug: "/",
    title: "Home",
  },
  {
    id: 2,
    slug: "/shop",
    title: "Shop",
  },
  {
    id: 3,
    slug: "/products",
    title: "Products",
  },
];

export default function RootLayout({ children }) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen">
          <header className="w-full bg-blue-300 text-gray-500">
            <nav>
              <ul className="flex ">
                {navLinks.map((item) => {
                  // const isActive = pathname.startsWith(item.slug);
                  const isActive = pathname === item.slug;
                  return (
                    <li className="p-4" key={item.id}>
                      <Link
                        className={
                          isActive
                            ? "font-bold text-violet-900"
                            : ""
                        }
                        href={item.slug}
                      >
                        {item.title}
                      </Link>
                    </li>
                  );
                })}
              </ul>
            </nav>
          </header>
          <div className="flex-1 p-4">{children}</div>
          <footer className="p-4 bg-slate-100">User RootLayout Footer</footer>
        </div>
      </body>
    </html>
  );
}
